### ISSUE TITLE
Order Total and Points Awarded showing up in /trips, but not on /account/dashboard

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#167]
Oddly enough, it shows up properly in both on mobile.  Actually, if you make the desktop browser smaller, the Order Total and Points Awarded values DO show up...

On a positive note, the trip tracked properly, so no orphan transaction. Awesome!

Here are both screenshots

![uploads/ed5fcc6c-d0ac-4f1b-80d4-8864e34f2a15/Screen Shot 2017-06-01 at 5.51.52 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fed5fcc6c-d0ac-4f1b-80d4-8864e34f2a15%2FScreen+Shot+2017-06-01+at+5.51.52+PM.png)

![uploads/d8b8619e-f6c6-4d18-8f2b-27357706762e/Screen Shot 2017-06-01 at 5.51.36 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fd8b8619e-f6c6-4d18-8f2b-27357706762e%2FScreen+Shot+2017-06-01+at+5.51.36+PM.png)

**Comment by cgladue** [comment]
Awesome great news :)

I'm sure it's something simple on why it's not displaying.

**Comment by Dwells7583** [comment]
updated.

**Comment by robgpeak** [comment]
This was marked as updated, but the issue still remains as described.  When the screen resolution is full size, the values do NOT show up in dashboard, but they do show up in trips.

**Comment by Dwells7583** [comment]
I believe those were not published just yet.  @cgladue can you make sure my most recent commits are published.

**Comment by cgladue** [comment]
Yep, i have published all the commits up to now.

**Comment by robgpeak** [comment]
@Dwells7583 I just did a clean (all cookies, browser history and cache) refresh...  Logged out, and logged back in, and I am still getting the same results.

**Comment by Dwells7583** [comment]
@robgpeak  What browser, what OS?

**Comment by robgpeak** [comment]
Chrome and Firefox in iOS 10.10.3 Yosemite and also on Morgan's machine in Chrome v.58.0.3 and her iOS is 10.11.3 El Capitan

I don't think you will be able to replicate it because you you don't have any "completed shopping trips"  Meaning, we are talking about just the CVS purchase that I had of $13.99 which resulted in the issuance of 28 points.  That information IS showing up in /trips, just not in Dashboard.

**Comment by robgpeak** [comment]
log in with robg@peakmarketing.com and pw: 6TzY@7bgx and you can see it, or not see it:)

**Comment by Dwells7583** [comment]
@cgladue can you add some completed shopping trips in my account so i can see it locally to test this issue? I cannot log into robs account on my local machine.

**Comment by Dwells7583** [comment]
the derek.test@searlesgraphics.com

**Comment by cgladue** [comment]
how about now,

**Comment by Dwells7583** [comment]
@robgpeak @cgladue My latest commit has the fix. Thanks.

**Comment by cgladue** [comment]
@Dwells7583 @robgpeak changes published
